language:  python
python:
  - "3.9"

install:
  - pip install -r requirements.txt

script:
  - coverage run -m pytest tests
  - pylint -- errors-only --disable=C,R maintenance_accounting

after_script:
  - coveralls
